### ISSUE TITLE
Jackcast service doesn't autostart

### ISSUE THREAD

**Issue by davidbroster** [wil3/jackcast#11]
built on a raspberry Pi 3b running Ubuntu Server (LTE 32bit) v20.04 and runs perfectly IF (and only IF) I ssh login to a terminal as user=ubuntu, then the jackcast service starts.  Otherwise no start.  If I close the terminal session  Ubuntu server 20.4It all works perfectly. If I log out of the terminal session the service continues to run.  After reading through several issues and email with Wil then I built using the instruction list below.

wget https://raw.githubusercontent.com/wil3/jackcast/master/platforms/ubuntu/install.sh .
chmod +x install.sh
sudo bash install.sh
sudo rm -rf /srv/www/jackcast
sudo mkdir -p /srv/www
cd /srv/www
sudo git clone https://github.com/wil3/jackcast.git
sudo chown -R ubuntu:ubuntu jackcast
cd jackcast
sudo apt-get install python3-venv -y
python3 -m venv env
source env/bin/activate
pip3 install wheel
pip3 install .
sudo rm /etc/nginx/sites-enabled/default
sudo cp /srv/www/jackcast/platforms/ubuntu/etc/nginx/sites-available/jackcast /etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/jackcast /etc/nginx/sites-enabled
sudo cp /srv/www/jackcast/platforms/ubuntu/etc/systemd/user/jackcast.service /etc/systemd/user/
sudo reboot
.................... (re)login
systemctl --user start jackcast
systemctl --user enable jackcast
.................... close terminal session and jackcast continues to run.

After a power cycle I need to login as 'ubuntu' before the service will restart.

Content of 'jackcast.service' is:
[Unit]
Description=uWSGI instance to serve Jackcast
After=network.target
After=pulseaudio.service
Requires=pulseaudio.service

[Service]
WorkingDirectory=/srv/www/jackcast
Environment="PATH=/srv/www/jackcast/env/bin:/usr/bin"
Environment=PYTHONUNBUFFERED=TRUE
ExecStart=/srv/www/jackcast/env/bin/gunicorn wsgi:app -c /srv/www/jackcast/platforms/ubuntu/gunicorn.conf.py

[Install]
WantedBy=default.target

.............................
permissions on /etc/systemd/user/jackcast.service  are:
-rw-r--r-- 1 root root  495 Nov  6 15:12 jackcast.service

Can anyone offer a "cure" ? / or spot where I went wrong ?

**Comment by wil3** [comment]
Can you provide the output of,

`ls /var/lib/systemd/linger`

**Comment by davidbroster** [comment]
ubuntu@jackcast:~$ ls /var/lib/systemd/linger
root

**Comment by davidbroster** [comment]
I've never worked with a service in the /etc/systemd/user/ folder before .....

**Comment by wil3** [comment]
You need to configure the user running the jackcast service to start at boot. Its in the install script, maybe you cloned the repo before the change? This is how you do it, https://github.com/wil3/jackcast/blob/master/platforms/ubuntu/install.sh#L46-L50

Afterwards the user should appear in `ls /var/lib/systemd/linger`

**Comment by wil3** [comment]
@davidbroster did that fix it?

**Comment by davidbroster** [comment]
Hi Wil, sorry for the delay, I've been away from my desk for a couple of days (cleaning the house gutters while it wasn't raining :-) AND the answer is - YES that fixed it ...... I also ordered (arriving Monday) a stereo input dongle [Behringer UCA202] like dangermouse69 .... then I'll play with the buffering and see if I can reliably reduce the delay - and report back in a week or two.
Keep in touch if there are any further development your end .... e.g. Chromecast or Bluetooth ..... Oh .... and .... MANY THANKS
