### ISSUE TITLE
Good solution

### ISSUE THREAD

**Issue by hwahlis** [wil3/jackcast#12]
Great work on this.
I got i working on my laptop using "jackcast" as output. Im sure I can get it to work on a RPI with Line in.
The thing is I am running a couple of amlogic boxes with Coreelec.
Do you know if it is possible to install direct on the Coreelecbox ? Feels kind of silly to get another SBC to send audio to the Sonos speakers.

/Henrik

**Comment by wil3** [comment]
Thanks! I'm not really sure about that, I've never worked with CoreELEC. Under the hood jackcast is using pulseaudio, nginx and python. If you can get those running it might be possible to port. To simplify the environment setup I wrote this bash script, https://github.com/wil3/jackcast/blob/master/platforms/ubuntu/install.sh it may give you an idea of the system dependencies.

**Comment by hwahlis** [comment]
Thanks for your reply.
I put your solution on feature request in the CoreElec forum I hope thats
okay with you (linked to the jackcast github page)

/Henrik
