### ISSUE TITLE
Jackcast crashes if no Sonos speakers are found with: "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by VictorvandenHoven** [wil3/jackcast#16]
Hi,

I tried to follow the guide and when I got to the end I am getting a 502 Bad Gateway when accessing the page.

When rebooting the raspberrypi3 I got this in the syslog:

Sep  8 10:09:13 jackcast systemd[1885]: Startup finished in 2.686s.
Sep  8 10:09:49 jackcast systemd-timesyncd[1551]: Initial synchronization to time server 91.189.89.199:123 (ntp.ubuntu.com).
Sep  8 10:09:49 jackcast gunicorn[1915]: [2021-09-08 10:09:49 +0000] [1915] [INFO] Starting gunicorn 20.1.0
Sep  8 10:09:49 jackcast gunicorn[1915]: [2021-09-08 10:09:49 +0000] [1915] [INFO] Listening at: unix:/tmp/jackcast.sock (1915)
Sep  8 10:09:49 jackcast gunicorn[1915]: [2021-09-08 10:09:49 +0000] [1915] [INFO] Using worker: gevent
Sep  8 10:09:49 jackcast gunicorn[1935]: [2021-09-08 10:09:49 +0000] [1935] [INFO] Booting worker with pid: 1935
Sep  8 10:09:55 jackcast systemd[1]: systemd-hostnamed.service: Succeeded.
Sep  8 10:09:57 jackcast gunicorn[1935]: [2021-09-08 10:09:57 +0000] [1935] [ERROR] Exception in worker process
Sep  8 10:09:57 jackcast gunicorn[1935]: Traceback (most recent call last):
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Sep  8 10:09:57 jackcast gunicorn[1935]:     worker.init_process()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
Sep  8 10:09:57 jackcast gunicorn[1935]:     super().init_process()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Sep  8 10:09:57 jackcast gunicorn[1935]:     self.load_wsgi()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Sep  8 10:09:57 jackcast gunicorn[1935]:     self.wsgi = self.app.wsgi()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Sep  8 10:09:57 jackcast gunicorn[1935]:     self.callable = self.load()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Sep  8 10:09:57 jackcast gunicorn[1935]:     return self.load_wsgiapp()
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Sep  8 10:09:57 jackcast gunicorn[1935]:     return util.import_app(self.app_uri)
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Sep  8 10:09:57 jackcast gunicorn[1935]:     mod = importlib.import_module(module)
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Sep  8 10:09:57 jackcast gunicorn[1935]:     return _bootstrap._gcd_import(name[level:], package, level)
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/wsgi.py", line 1, in <module>
Sep  8 10:09:57 jackcast gunicorn[1935]:     from jackcast import app
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/jackcast/__init__.py", line 14, in <module>
Sep  8 10:09:57 jackcast gunicorn[1935]:     jc.speaker = Sonos(80)
Sep  8 10:09:57 jackcast gunicorn[1935]:   File "/srv/www/jackcast/jackcast/speakers/sonos.py", line 67, in __init__
Sep  8 10:09:57 jackcast gunicorn[1935]:     for device in devices:
**Sep  8 10:09:57 jackcast gunicorn[1935]: TypeError: 'NoneType' object is not iterable**
Sep  8 10:09:57 jackcast gunicorn[1935]: [2021-09-08 10:09:57 +0000] [1935] [INFO] Worker exiting (pid: 1935)
Sep  8 10:09:58 jackcast gunicorn[1915]: [2021-09-08 10:09:58 +0000] [1915] [INFO] Shutting down: Master
Sep  8 10:09:58 jackcast gunicorn[1915]: [2021-09-08 10:09:58 +0000] [1915] [INFO] Reason: Worker failed to boot.
Sep  8 10:09:58 jackcast pulseaudio[1891]: Too many underruns, increasing latency to 12.00 ms
Sep  8 10:09:58 jackcast systemd[1885]: jackcast.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep  8 10:09:58 jackcast systemd[1885]: jackcast.service: Failed with result 'exit-code'.

Can it be that jackcast gives this error because I have no wireless Sonos speakers active?
I am just preparing a rpi3 for a friend, I do not have Sonos myself.

When I start jackcast manually I get:

ubuntu@jackcast:~$  /srv/www/jackcast/env/bin/gunicorn wsgi:app -c /srv/www/jackcast/platforms/ubuntu/gunicorn.conf.py
[2021-09-08 10:22:34 +0000] [2053] [INFO] Starting gunicorn 20.1.0
[2021-09-08 10:22:34 +0000] [2053] [INFO] Listening at: unix:/tmp/jackcast.sock (2053)
[2021-09-08 10:22:34 +0000] [2053] [INFO] Using worker: gevent
[2021-09-08 10:22:34 +0000] [2055] [INFO] Booting worker with pid: 2055
[2021-09-08 10:22:35 +0000] [2055] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'wsgi'**
[2021-09-08 10:22:35 +0000] [2055] [INFO] Worker exiting (pid: 2055)
[2021-09-08 10:22:35 +0000] [2053] [INFO] Shutting down: Master
[2021-09-08 10:22:35 +0000] [2053] [INFO] Reason: Worker failed to boot.

Any Idea?

Kind Regards Victor

**Comment by wil3** [comment]
Hi @VictorvandenHoven, yes the line that it is crashing at is because it is searching for Sonos devices and then it assumes it will return at least one. Since there are none it crashes. PRs welcome to handle this more elegantly.

**Comment by VictorvandenHoven** [comment]
> PRs welcome to handle this more elegantly.

Not sure if it is more elegantly, but I created a PR
