### ISSUE TITLE
Code not working out

### ISSUE THREAD

**Issue by dangermouse69** [wil3/jackcast#9]
Hi Wil,

Amazing that you have pulled this together. Unfortunately, I'm having problems with the code you have put in the description to manually build Jackcast.

Are you any closer to building an image? 

Thanks

Danny Moore

**Comment by wil3** [comment]
Thanks Danny!

I haven't yet, was waiting to see if there was any interest first. In the mean time if you explain the issue you have having I can try and help you through it.

**Comment by dangermouse69** [comment]
Hi Wil,

Thanks for getting back to me. This is such a great idea. I love my Sonos speakers but can’t justify the cost of the Connect or Amp (or their new equivalents)

Firstly I’m an audio buff more than a coder although I have dabbled.

I’m copying the scripts verbosely and I’m a bit confused where it line wraps - is it one command etc.

It seems to have a problem loading a visual python environment and loading Nginx.

It also struggles deleting and directories and files when loading Jackcast.

Maybe I need a idiots guide :-)

Again, great idea and thanks for sharing. I so need this to work as I have a load of 80s and 90s vinyl to play.

Danny Moore

**Comment by dangermouse69** [comment]
Hi Wil

Think I have made some progress.

When I try and reach jackcast.local or its IP address I’m getting a 502 Bad Gateway. Any ideas.

Also can you check to see what services you expect to be running so I can check they are running my side.

Thanks

Danny

**Comment by dangermouse69** [comment]
Hi Wil,

Have checked the Nginx logs and this is what I am seeing.

2020/07/26 23:04:04 [crit] 1266#1266: *28 connect() to unix:/tmp/jackcast.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.0.40, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/tmp/jackcast.sock:/favicon.ico", host: "jackcast.local"

**Comment by ol1ver5** [comment]
Hello, 

the problem is most likely that the service "jackcast.service" is not started.  Please check if you can access the website when starting the process manually "/srv/www/jackcast/env/bin/gunicorn wsgi:app -c /srv/www/jackcast/platforms/ubuntu/gunicorn.conf.py".

If that is the case please check if the what the problem might be with "systemd-analyze verify jackcast.service".  In my case the issue is related to pulse audio. (jackcast.service: Failed to create jackcast.service/start: Unit pulseaudio.service not found.)

i am still investigating and think it has something todo with my soundcard, but thought i´d share my findings. 

Cheers ol1ver

**Comment by dangermouse69** [comment]
Hi ol1ver

You are right - I checked and the jackcast service is not running.

I tried to start the process manually and I got this

root@jackcast:/# /srv/www/jackcast/env/bin/gunicorn wsgi:app -c /srv/www/jackcast/platforms/ubuntu/gunicorn.conf.py
bash: /srv/www/jackcast/env/bin/gunicorn: 
No such file or directory

When is unicorn installed?

I tried running systemd-analyze verify jackcast.service manually too and got this

root@jackcast:/# systemd-analyze verify jackcast.service
/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file accordingly.
snap-core18-1882.mount: Unit is bound to inactive unit dev-loop2.device. Stopping, too.
Unit jackcast.service not found.

Thanks

Danny

**Comment by wil3** [comment]
@ol1ver5 if you are having trouble please open a separate issue and I'll try and give you a hand. 

@dangermouse69 One problem I see in your command is you are running as root. Pulse audio needs to run in user mode and generally its a bad idea to be running as root, lots of unexpected things can happen. The default user for the RPI 4 with the required Ubuntu server is `ubuntu`.

Did you follow the installation instructions [here](https://github.com/wil3/jackcast#installation)? Under "Clone the repo and install Jackcast" those commands create the virtual environment /srv/www/jackcast/env/bin and install all the dependencies including Gunicorn. 

However looking at it again there are some details missing from the instructions. 

Try execute the following command:
```
ls -l /srv/www
```
If the user and group says `root` for the jackcast directory that's incorrect. I'd start off by first deleting /srv/www/jackcast and starting over with the following commands. You can delete the directory with,
```
sudo rm -r /srv/www/jackcast
```
If it prompts you asking if you want to delete write protected files ctrl + c out of that and force the removal with
```
sudo rm -rf /srv/www/jackcast
```

Then try reinstalling with,
```
sudo mkdir -p /srv/www
cd /srv/www
sudo git clone https://github.com/wil3/jackcast.git
sudo chown -R ubuntu:ubuntu jackcast
cd jackcast
python3 -m venv env
source env/bin/activate
pip3 install wheel # Is needed by gevent
pip3 install .
```

The rest of the instructions look OK. If that doesn't work for any reason let me know.

**Comment by dangermouse69** [comment]
Hi Wi,

Yes I follow the instructions that you linked to.

I followed what you said and all went ok. I ran ls - l /srv/www to double check and all looks ok.

ubuntu@jackcast:/$ ls -l /srv/www
total 4
drwxr-xr-x 8 ubuntu ubuntu 4096 Jul 28 08:22 jackcast

Rebooted the server and tried to connect via jackcast.local and IP address and still getting the 502 error

These are the services running after a reboot.

[ - ]  alsa-utils
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  atd
 [ + ]  avahi-daemon
 [ - ]  console-setup.sh
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  dbus
 [ - ]  hwclock.sh
 [ + ]  irqbalance
 [ - ]  iscsid
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ - ]  lvm2
 [ - ]  lvm2-lvmpolld
 [ + ]  multipath-tools
 [ + ]  nginx
 [ - ]  open-iscsi
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  procps
 [ - ]  pulseaudio-enable-autospawn
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ + ]  ssh
 [ + ]  udev
 [ + ]  ufw
 [ + ]  unattended-upgrades
 [ - ]  uuidd
 [ - ]  x11-common

There is no jackcast service running. I manually tried running jackcast as suggested by Ol1ver and this is what I got back

ubuntu@jackcast:/var/log/nginx$ /srv/www/jackcast/env/bin/gunicorn wsgi:app -c /srv/www/jackcast/platforms/ubuntu/gunicorn.conf.py
[2020-07-28 08:50:07 +0000] [1790] [INFO] Starting gunicorn 20.0.4
[2020-07-28 08:50:07 +0000] [1790] [INFO] Listening at: unix:/tmp/jackcast.sock (1790)
[2020-07-28 08:50:07 +0000] [1790] [INFO] Using worker: gevent
[2020-07-28 08:50:07 +0000] [1793] [INFO] Booting worker with pid: 1793
[2020-07-28 08:50:07 +0000] [1793] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/www/jackcast/env/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-07-28 08:50:07 +0000] [1793] [INFO] Worker exiting (pid: 1793)
[2020-07-28 08:50:07 +0000] [1790] [INFO] Shutting down: Master
[2020-07-28 08:50:07 +0000] [1790] [INFO] Reason: Worker failed to boot.

Nginx error log shows

2020/07/28 09:10:05 [crit] 1271#1271: *27 connect() to unix:/tmp/jackcast.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.0.40, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/jackcast.sock:/", host: “jackcast.local"

Should I start over with a clean build as Ubuntu user rather than root?

Thanks

**Comment by wil3** [comment]
Yea that's not the correct way to run manually. You get that error because none of the other dependencies are on the path. If you wanted to do that you'd first have to start the virtual environment then execute the script `jackcast/devel/run.sh`.

Before going through all that just reboot and check the status of the service. I think off hand it is `systemctl --user status jackcast` (note no sudo). Paste the output here.

If it says the service doesn't exist then you must have skipped those installation instructions.

**Comment by wil3** [comment]
Well I'm glad someone is testing this out because there may be more missing from the installation instructions.

After you copy jackcast.service you also need to start and enable the service. Try this no sudo,

```
systemctl --user start jackcast
systemctl --user enable jackcast
```

Then check the status, let me know if that works.

**Comment by ol1ver5** [comment]
Hey Wil, 

enabling the service as user and not as root is a good hint, that at least solved the autostart issue on my side. As a lot of time the issue was in front of the keyboard :)

Thanks,
Oliver

**Comment by dangermouse69** [comment]
It Lives…

Amazing so far so good.

I had to change some of the install commands - mainly due to permissions.

Here is the modified code (plus the changes you sent through Wil)

Initially I had to run Jackcast manually, but on a reboot all looks and sounds OK.

Super happy here in the UK

Danny

**Comment by dangermouse69** [comment]
Sorry here is the code.

wget https://raw.githubusercontent.com/wil3/jackcast/master/platforms/ubuntu/install.sh .
chmod +x install.sh
sudo bash install.sh



sudo mkdir -p /srv/www
cd /srv/www
sudo git clone https://github.com/wil3/jackcast.git
sudo chown -R ubuntu:ubuntu jackcast
cd jackcast
sudo apt-get install python3-venv
python3 -m venv env
source env/bin/activate
pip3 install wheel # Is needed by gevent
pip3 install .


sudo rm /etc/nginx/sites-enabled/default
cp /srv/www/jackcast/platforms/ubuntu/etc/nginx/sites-available/jackcast
/etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/jackcast /etc/nginx/sites-enabled

sudo cp /srv/www/jackcast/platforms/ubuntu/etc/systemd/user/jackcast.service
/etc/systemd/user/


sudo reboot

**Comment by dangermouse69** [comment]
Now have it working, so far so good. I have raised another issue regarding sound quality.

**Comment by wil3** [comment]
Updated the readme with your steps, thanks again!
